# Generated by Django 2.0.7 on 2018-09-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180912_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='tag',
            new_name='tags',
        ),
    ]
