# Generated by Django 2.0.7 on 2018-09-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='post_local_id',
            field=models.CharField(default='', max_length=900),
        ),
    ]
