# Generated by Django 2.0.7 on 2018-10-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
    ]
