# Generated by Django 2.0.7 on 2018-10-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='architect',
            field=models.CharField(max_length=255),
        ),
    ]
